version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn billingsystem.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db

volumes:
  #postgres_data:
  static_volume:

  # web:
  #   build: .
  #   command: gunicorn billingsystem.wsgi:application --bind 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.prod
    # depends_on:
    #   - db
#   db:
#     image: postgres:12.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.prod.db

# volumes:
#   postgres_data:
