version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn billingsystem.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env.prod

volumes:
  static_volume: